# Generated by Django 4.0.8 on 2022-11-25 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
