# Generated by Django 4.0.8 on 2022-11-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0003_post_delete_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(default='', max_length=999),
        ),
        migrations.AddField(
            model_name='post',
            name='created_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='modified_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
