# Generated by Django 4.0.8 on 2022-11-25 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0005_account'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account',
            new_name='Users',
        ),
    ]
