# Generated by Django 4.0.8 on 2022-11-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0008_user_username_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='User.username', max_length=20),
        ),
    ]
