# Generated by Django 4.0.8 on 2022-11-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0011_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
