# Generated by Django 4.0.8 on 2022-11-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0013_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='times',
            field=models.IntegerField(default=0),
        ),
    ]
