# Generated by Django 4.0.8 on 2022-11-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0014_post_times'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a genre', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='genre',
            field=models.ManyToManyField(help_text='Select a genre for this book', to='function.genre'),
        ),
    ]
