# Generated by Django 4.0.8 on 2022-11-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0017_remove_post_genre_post_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
