# Generated by Django 4.0.8 on 2022-11-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0019_post_genre_name_alter_post_body_alter_post_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(default='', max_length=999),
        ),
    ]
